---
      # tasks file for docker
      - name: create image docker
        docker_image:
          name: devops
          build:
           path: /var/lib/jenkins/workspace/devops
           pull: no
           source: build
           state: present
      - name: run container docker
        docker_container
        name: application_container
        image: devops:latest
        state: started
        recreate: true
        ports:
         - "4200:80"
